using JobHunter.Domain.Enums;

namespace JobHunter.Application.Profiles.Dtos;

/// <summary>Profilin tamami: ana alanlar + tum alt listeler. FullName/Email User tablosundan gelir.</summary>
public record ProfileResponse(
    Guid Id,
    string FullName,
    string Email,
    string? Headline,
    string? Summary,
    string? PhoneNumber,
    string? City,
    string? Country,
    string? District,
    string? AddressLine,
    string? PostalCode,
    DateOnly? DateOfBirth,
    Gender? Gender,
    MaritalStatus? MaritalStatus,
    string? Nationality,
    MilitaryServiceStatus? MilitaryServiceStatus,
    DateOnly? MilitaryPostponedUntil,
    IReadOnlyList<string> DriverLicenseClasses,
    int? DriverLicenseYear,
    bool? CanTravel,
    bool? IsSmoker,
    bool? HasDisability,
    string? LinkedInUrl,
    string? GitHubUrl,
    string? PortfolioUrl,
    int? YearsOfExperience,
    decimal? ExpectedSalary,
    string? SalaryCurrency,
    int? NoticePeriodDays,
    WorkMode? PreferredWorkMode,
    bool OpenToRelocation,
    bool RequiresVisaSponsorship,
    string? WorkAuthorization,
    IReadOnlyList<string> Skills,
    Guid? DefaultCvId,
    string? DefaultCvName,
    IReadOnlyList<WorkExperienceResponse> WorkExperiences,
    IReadOnlyList<EducationResponse> Educations,
    IReadOnlyList<LanguageResponse> Languages,
    IReadOnlyList<ScreeningAnswerResponse> ScreeningAnswers,
    IReadOnlyList<CertificateResponse> Certificates,
    IReadOnlyList<ReferenceResponse> References,
    IReadOnlyList<CustomFieldResponse> CustomFields,
    // Tum politikali alanlarin gecerli politikasi (varsayilanlar + kullanicinin secimleri).
    IReadOnlyDictionary<string, AutofillPolicy> FieldPolicies,
    DateTime CreatedAt,
    DateTime? UpdatedAt);
